Parameters:
  CodeCommitRepoName:
    Type: String
    Default: demo-springboot-repository
    AllowedPattern: "[A-Za-z0-9-]+"
  CodeBuildName:
    Type: String
    Default: demo-springboot-to-fargate-codebuild
    AllowedPattern: "[A-Za-z0-9-]+"
Resources:
  DemoCodeCommit:
    Type: AWS::CodeCommit::Repository
    Properties: 
      RepositoryDescription: Kode program untuk tutorial deploy Java Springboot ke AWS Fargate.
      RepositoryName: !Ref CodeCommitRepoName
      Tags: 
        - Key: department
          Value: demo
  S3UntukCodePipeline:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: bucket-untuk-codepipeline
      Tags: 
        - Key: department
          Value: demo
  DemoCodeBuild:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Ref CodeBuildName
      Description: Demo CodeBuild untuk untuk tutorial deploy Java Springboot ke AWS Fargate.
      ServiceRole: arn:aws:iam::623127157773:role/service-role/codebuild-hello-world-sederhana-service-role
      Artifacts:
        Type: no_artifacts
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:4.0
        PrivilegedMode: true
      Source:
        Location: https://git-codecommit.ap-southeast-1.amazonaws.com/v1/repos/demo-springboot-repository
        Type: CODECOMMIT
      TimeoutInMinutes: 10
      Tags:
        - Key: department
          Value: demo
  DemoCodePipeline:
    DependsOn: S3UntukCodePipeline
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: demo-springboot-to-fargate-codepipeline
      RoleArn: arn:aws:iam::623127157773:role/service-role/AWSCodePipelineServiceRole-ap-southeast-1-Unsimple-Hello-World
      ArtifactStore:
        Type: S3
        Location: bucket-untuk-codepipeline
      Stages:
        - Name: Source
          Actions:
          - Name: JavaSource
            ActionTypeId:
              Category: Source
              Owner: AWS
              Version: 1
              Provider: CodeCommit
            OutputArtifacts:
            - Name: SourceCode
            Configuration:
              RepositoryName: !Ref CodeCommitRepoName
              BranchName: master
            RunOrder: 1
        - Name: Build
          Actions:
          - Name: JavaBuild
            InputArtifacts:
              - Name: SourceCode
            ActionTypeId:
              Category: Build
              Owner: AWS
              Version: 1
              Provider: CodeBuild
            Configuration:
              ProjectName: !Ref CodeBuildName
            OutputArtifacts:
            - Name: BuiltCode
            RunOrder: 2
  DemoECR:
    Type: AWS::ECR::Repository
    DependsOn: DemoCodeBuild
    Properties:
      RepositoryName: demo-springboot-to-fargate-ecr
      Tags: 
        - Key: department
          Value: demo
Outputs:
  CodeCommitOutput:
    Description: Nama CodeCommit.
    Value: !GetAtt DemoCodeCommit.Name
    Export:
      Name: CodeCommitName
  CodeBuildOutput:
    Description: Nama CodeBuild.
    Value: !Ref DemoCodeBuild
    Export:
      Name: CodeBuildProjectName
  S3UntukCodePipelineOutput:
    Description: Nama S3 Bucket.
    Value: !Ref S3UntukCodePipeline
    Export:
      Name: CodePipelineS3Bucket 